### ISSUE TITLE
User Interface Style

### ISSUE THREAD

**Issue by ahmetbekcan** [ahmetbekcan/CASY#5]
Some styling is needed to make the chatbot look better. Temporary css and config files are added into the project. They should be modified to make the app visually appealing.

- ui_components/style.css file should be modified
- .streamlit/config.toml file can be [modified ](https://docs.streamlit.io/develop/concepts/configuration/theming)to change global settings

**Comment by sila-98** [comment]
I have updated the .streamlit/config.toml file to enhance the chatbot's UI. Background colors, text colors are customized. Hence style.css is updated for further improvements.

**Comment by sila-98** [comment]
Done
